[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
firewall = "5ZtXDT2Qs1esK3UR61une1fqRkV8KQ7tssMqWXNUFXX"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -t 1000000 programs/firewall/tests/**/*.ts"

[hooks]
